version: '3.4'

services:
  app:
    container_name: app
    build: 
      context: ./
      dockerfile: ./docker/go/Dockerfile
    ports: 
      - "8080:8080"
    tty: true
    volumes:
      - ./:/go/src/app
    environment:
      DB_DOMAIN: test-db
      DB_PASS: pass
      DB_PORT: 3306
    depends_on:
      - db
  
  db:
    container_name: test-db
    image: mysql:8.0.29
    platform: linux/x86_64
    command: --default-authentication-plugin=mysql_native_password
    ports:
      - "3306:3306"
    volumes:
      - ./docker/mysql/initdb:/docker-entrypoint-initdb.d:ro
      - ./docker/mysql/db/:/var/lib/mysql
      - ./docker/mysql/conf:/etc/mysql/conf.d:ro
    user: 1000:1000
    environment:
      MYSQL_ROOT_PASSWORD: pass