name: test-service-container
run-name: run db test
on: [push]

jobs:
  test-db:
    runs-on: ubuntu-latest
  
    env:
      DB_DOMAIN: localhost
      DB_PASS: pass
      DB_PORT: 3306

    services:
      mysql:
        image: mysql:8.0.29
        env:
          MYSQL_ROOT_PASSWORD: ${{ env.DB_PASS }}
        ports:
          - 3306:3306
        options: >-
          --health-cmd "mysqladmin ping"
          --health-interval 10s
          --health-timeout 5s
          --health-retries 5
      
    steps:
      - uses: actions/checkout@v3

      - name: Set up Go
        uses: actions/setup-go@v3
        with:
          go-version: '1.19'
      
      - name: Initialize MySQL
        run: mysql -h 127.0.0.1 -P 3306 -u root -p${{ env.DB_PASS }} < ./docker/mysql/initdb.d/init.sql
      
      - name: Run Insert
        run: go run .
      
      - name: Run Test
        run: go test . -v
